# -*- coding: utf-8 -*-
"""Copy of discovery model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16aqXnh_LhNcQc77pk-RcWuw3LWv7TeLF

discovery model
"""

"""Discovery Model"""

__docformat__ = "google"

import pandas as pd

from financetoolkit.fmp_model import get_financial_data
from financetoolkit.utilities import error_model


def _rename_columns(df: pd.DataFrame, rename_map: dict[str, str]) -> pd.DataFrame:
    """
    Rename columns safely: avoid duplicate field names by prioritizing a set order.
    """
    # If multiple source keys map to one target, safely assign.
    for target_name in set(rename_map.values()):
        sources = [k for k, v in rename_map.items() if v == target_name]
        for s in sources:
            if s in df.columns:
                df[target_name] = df[s]
    # Also rename directly for fields not processed above
    df = df.rename(columns={k: v for k, v in rename_map.items() if k in df.columns and v != k})
    return df


def get_instruments(
    api_key: str,
    query: str,
    search_method: str = "name",
    user_subscription: str = "Free",
) -> pd.DataFrame:
    """
    Get a list of instruments based on a query.
    """
    url = f"https://financialmodelingprep.com/stable/search-{search_method}?query={query}&apikey={api_key}"

    try:
        df = get_financial_data(url=url, user_subscription=user_subscription)
    except Exception as e:
        raise ConnectionError(f"Failed to fetch data: {e}")

    error_model.check_for_error_messages({"SEARCH_INSTRUMENTS": df}, user_subscription=user_subscription)

    if df.empty:
        return pd.DataFrame()

    df = _rename_columns(df, {
        "symbol": "Symbol",
        "name": "Name",
        "companyName": "Name",
        "currency": "Currency",
        "exchangeFullName": "Exchange",
        "exchange": "Exchange Code",
        "cusip": "CUSIP",
        "cik": "CIK",
        "isin": "ISIN",
        "marketCap": "Market Cap",
    })

    if "Symbol" in df.columns:
        df = df.set_index("Symbol")
    return df


def get_stock_screener(
    api_key: str,
    market_cap_higher: int | None = None,
    market_cap_lower: int | None = None,
    price_higher: int | None = None,
    price_lower: int | None = None,
    beta_higher: int | None = None,
    beta_lower: int | None = None,
    volume_higher: int | None = None,
    volume_lower: int | None = None,
    dividend_higher: int | None = None,
    dividend_lower: int | None = None,
    is_etf: bool | None = None,
    user_subscription: str = "Free",
) -> pd.DataFrame:
    """
    Get a list of stocks based on screening criteria.
    """
    url = f"https://financialmodelingprep.com/stable/company-screener?apikey={api_key}"

    params = {
        "marketCapMoreThan": market_cap_higher,
        "marketCapLowerThan": market_cap_lower,
        "priceMoreThan": price_higher,
        "priceLowerThan": price_lower,
        "betaMoreThan": beta_higher,
        "betaLowerThan": beta_lower,
        "volumeMoreThan": volume_higher,
        "volumeLowerThan": volume_lower,
        "dividendMoreThan": dividend_higher,
        "dividendLowerThan": dividend_lower,
        "isEtf": str(is_etf).lower() if is_etf is not None else None,
    }
    for key, value in params.items():
        if value is not None:
            url += f"&{key}={value}"

    try:
        df = get_financial_data(url=url, user_subscription=user_subscription)
    except Exception as e:
        raise ConnectionError(f"Failed to fetch data: {e}")

    if df.empty:
        raise ValueError("No stocks found matching the query.")

    df = _rename_columns(df, {
        "symbol": "Symbol",
        "companyName": "Name",
        "marketCap": "Market Cap",
        "sector": "Sector",
        "industry": "Industry",
        "beta": "Beta",
        "price": "Price",
        "lastAnnualDividend": "Dividend",
        "volume": "Volume",
        "exchange": "Exchange",
        "exchangeShortName": "Exchange Code",
        "country": "Country",
        "currency": "Currency",
        "stockExchange": "Exchange",
    })

    df = df.drop(columns=["isEtf", "isActivelyTrading"], errors="ignore")
    if "Symbol" in df.columns:
        df = df.set_index("Symbol")
    return df


def get_stock_list(api_key: str, user_subscription: str = "Free") -> pd.DataFrame:
    """
    Get a list of stocks.
    """
    url = f"https://financialmodelingprep.com/stable/stock-list?apikey={api_key}"
    try:
        df = get_financial_data(url=url, user_subscription=user_subscription)
    except Exception as e:
        raise ConnectionError(f"Failed to fetch data: {e}")

    if df.empty:
        return pd.DataFrame()

    df = _rename_columns(df, {
        "symbol": "Symbol",
        "companyName": "Name",
    })

    if "Symbol" in df.columns:
        df = df.set_index("Symbol").sort_index()
    return df


def get_stock_quotes(api_key: str, user_subscription: str = "Free") -> pd.DataFrame:
    """
    Get realtime stock quotes.
    """
    url = f"https://financialmodelingprep.com/stable/stock/full/real-time-price?apikey={api_key}"
    try:
        df = get_financial_data(url=url, user_subscription=user_subscription)
    except Exception as e:
        raise ConnectionError(f"Failed to fetch data: {e}")

    if df.empty:
        return pd.DataFrame()

    df = _rename_columns(df, {
        "symbol": "Symbol",
        "bidSize": "Bid Size",
        "askPrice": "Ask Price",
        "volume": "Volume",
        "askSize": "Ask Size",
        "bidPrice": "Bid Price",
        "lastSalePrice": "Last Sale Price",
        "lastSaleSize": "Last Sale Size",
        "lastSaleTime": "Last Sale Time",
    })

    df = df.drop(columns=["fmpLast", "lastUpdated"], errors="ignore")
    if "Symbol" in df.columns:
        df = df.set_index("Symbol").sort_index()
    return df


def get_stock_shares_float(
    api_key: str, user_subscription: str = "Free"
) -> pd.DataFrame:
    """
    Get shares float for all stocks.
    """
    url = f"https://financialmodelingprep.com/api/v4/shares_float/all?apikey={api_key}"
    try:
        df = get_financial_data(url=url, user_subscription=user_subscription)
    except Exception as e:
        raise ConnectionError(f"Failed to fetch data: {e}")

    if df.empty:
        return pd.DataFrame()

    df = _rename_columns(df, {
        "symbol": "Symbol",
        "date": "Date",
        "freeFloat": "Free Float",
        "floatShares": "Float Shares",
        "outstandingShares": "Outstanding Shares",
    })

    if "Symbol" in df.columns:
        df = df.set_index("Symbol").sort_index()
    return df


def get_sectors_performance(
    api_key: str, user_subscription: str = "Free"
) -> pd.DataFrame:
    """
    Get sectors performance (historical).
    """
    url = f"https://financialmodelingprep.com/stable/historical-sectors-performance?apikey={api_key}"

    try:
        df = get_financial_data(url=url, user_subscription=user_subscription)
    except Exception as e:
        raise ConnectionError(f"Failed to fetch data: {e}")

    if df.empty:
        return pd.DataFrame()

    df = _rename_columns(df, {
        "date": "Date",
        "utilitiesChangesPercentage": "Utilities",
        "basicMaterialsChangesPercentage": "Basic Materials",
        "communicationServicesChangesPercentage": "Communication Services",
        "conglomeratesChangesPercentage": "Conglomerates",
        "consumerCyclicalChangesPercentage": "Consumer Cyclical",
        "consumerDefensiveChangesPercentage": "Consumer Defensive",
        "energyChangesPercentage": "Energy",
        "financialChangesPercentage": "Financial",
        "financialServicesChangesPercentage": "Financial Services",
        "healthcareChangesPercentage": "Healthcare",
        "industrialsChangesPercentage": "Industrials",
        "realEstateChangesPercentage": "Real Estate",
        "servicesChangesPercentage": "Services",
        "technologyChangesPercentage": "Technology",
    })

    if "Date" in df.columns:
        df = df.set_index("Date")
        try:
            df.index = pd.PeriodIndex(df.index, freq="D")
        except Exception:
            pass
        df = df.sort_index()
        df = df.dropna(how="all", axis=1)
    return df


def get_biggest_gainers(api_key: str, user_subscription: str = "Free") -> pd.DataFrame:
    """
    Get biggest gainers.
    """
    url = f"https://financialmodelingprep.com/stable/biggest-gainers?apikey={api_key}"
    try:
        df = get_financial_data(url=url, user_subscription=user_subscription)
    except Exception as e:
        raise ConnectionError(f"Failed to fetch data: {e}")

    if df.empty:
        return pd.DataFrame()

    df = _rename_columns(df, {
        "symbol": "Symbol",
        "name": "Name",
        "change": "Change",
        "price": "Price",
        "changesPercentage": "Change %",
        "exchange": "Exchange",
    })

    if "Symbol" in df.columns:
        df = df.set_index("Symbol").sort_index()
    return df


def get_biggest_losers(api_key: str, user_subscription: str = "Free") -> pd.DataFrame:
    """
    Get biggest losers.
    """
    url = f"https://financialmodelingprep.com/stable/biggest-losers?apikey={api_key}"
    try:
        df = get_financial_data(url=url, user_subscription=user_subscription)
    except Exception as e:
        raise ConnectionError(f"Failed to fetch data: {e}")

    if df.empty:
        return pd.DataFrame()

    df = _rename_columns(df, {
        "symbol": "Symbol",
        "name": "Name",
        "change": "Change",
        "price": "Price",
        "changesPercentage": "Change %",
        "exchange": "Exchange",
    })

    if "Symbol" in df.columns:
        df = df.set_index("Symbol").sort_index()
    return df


def get_most_active_stocks(
    api_key: str, user_subscription: str = "Free"
) -> pd.DataFrame:
    """
    Get most active stocks.
    """
    url = f"https://financialmodelingprep.com/stable/most-actives?apikey={api_key}"
    try:
        df = get_financial_data(url=url, user_subscription=user_subscription)
    except Exception as e:
        raise ConnectionError(f"Failed to fetch data: {e}")

    if df.empty:
        return pd.DataFrame()

    df = _rename_columns(df, {
        "symbol": "Symbol",
        "name": "Name",
        "change": "Change",
        "price": "Price",
        "changesPercentage": "Change %",
        "exchange": "Exchange",
    })

    if "Symbol" in df.columns:
        df = df.set_index("Symbol").sort_index()
    return df


def get_crypto_list(api_key: str, user_subscription: str = "Free") -> pd.DataFrame:
    """
    Get list of cryptocurrencies.
    """
    url = f"https://financialmodelingprep.com/stable/cryptocurrency-list?apikey={api_key}"
    try:
        df = get_financial_data(url=url, user_subscription=user_subscription)
    except Exception as e:
        raise ConnectionError(f"Failed to fetch data: {e}")

    if df.empty:
        return pd.DataFrame()

    df = _rename_columns(df, {
        "symbol": "Symbol",
        "name": "Name",
        "exchange": "Currency",
        "icoDate": "ICO Date",
        "circulatingSupply": "Circulating Supply",
        "totalSupply": "Total Supply",
    })

    if "Symbol" in df.columns:
        df = df.set_index("Symbol").sort_index()
    return df


def get_delisted_stocks(api_key: str, user_subscription: str = "Free") -> pd.DataFrame:
    """
    Get list of delisted companies.
    """
    url = f"https://financialmodelingprep.com/stable/delisted-companies?apikey={api_key}"
    try:
        df = get_financial_data(url=url, user_subscription=user_subscription)
    except Exception as e:
        raise ConnectionError(f"Failed to fetch data: {e}")

    if df.empty:
        return pd.DataFrame()

    df = _rename_columns(df, {
        "symbol": "Symbol",
        "companyName": "Name",
        "exchange": "Exchange",
        "ipoDate": "IPO Date",
        "delistedDate": "Delisted Date",
    })

    if "Symbol" in df.columns:
        df = df.set_index("Symbol").sort_index()
    return df


def get_forex_list(api_key: str, user_subscription: str = "Free") -> pd.DataFrame:
    """
    Get list of forex pairs.
    """
    url = f"https://financialmodelingprep.com/stable/symbol/available-forex-currency-pairs?apikey={api_key}"
    try:
        df = get_financial_data(url=url, user_subscription=user_subscription)
    except Exception as e:
        raise ConnectionError(f"Failed to fetch data: {e}")

    if df.empty:
        return pd.DataFrame()

    df = _rename_columns(df, {
        "symbol": "Symbol",
        "name": "Name",
        "currency": "Currency",
        "stockExchange": "Exchange",
        "exchangeShortName": "Exchange Code",
    })

    df = df.drop(columns=["Exchange Code"], errors="ignore")
    if "Symbol" in df.columns:
        df = df.set_index("Symbol").sort_index()
    return df


def get_commodity_list(api_key: str, user_subscription: str = "Free") -> pd.DataFrame:
    """
    Get list of commodities.
    """
    url = f"https://financialmodelingprep.com/stable/symbol/available-commodities?apikey={api_key}"
    try:
        df = get_financial_data(url=url, user_subscription=user_subscription)
    except Exception as e:
        raise ConnectionError(f"Failed to fetch data: {e}")

    if df.empty:
        return pd.DataFrame()

    df = _rename_columns(df, {
        "symbol": "Symbol",
        "name": "Name",
        "currency": "Currency",
        "stockExchange": "Exchange",
        "exchangeShortName": "Exchange Code",
    })

    df = df.drop(columns=["Exchange Code"], errors="ignore")
    if "Symbol" in df.columns:
        df = df.set_index("Symbol").sort_index()
    return df


def get_etf_list(api_key: str, user_subscription: str = "Free") -> pd.DataFrame:
    """
    Get list of ETFs.
    """
    url = f"https://financialmodelingprep.com/stable/etf/list?apikey={api_key}"
    try:
        df = get_financial_data(url=url, user_subscription=user_subscription)
    except Exception as e:
        raise ConnectionError(f"Failed to fetch data: {e}")

    if df.empty:
        return pd.DataFrame()

    df = _rename_columns(df, {
        "symbol": "Symbol",
        "name": "Name",
        "price": "Price",
        "exchange": "Exchange",
        "exchangeShortName": "Exchange Code",
        "type": "Type",
    })

    df = df.drop(columns=["Type"], errors="ignore")
    if "Symbol" in df.columns:
        df = df.set_index("Symbol").sort_index()
    return df


def get_index_list(api_key: str, user_subscription: str = "Free") -> pd.DataFrame:
    """
    Get list of indexes.
    """
    url = f"https://financialmodelingprep.com/stable/symbol/available-indexes?apikey={api_key}"
    try:
        df = get_financial_data(url=url, user_subscription=user_subscription)
    except Exception as e:
        raise ConnectionError(f"Failed to fetch data: {e}")

    if df.empty:
        return pd.DataFrame()

    df = _rename_columns(df, {
        "symbol": "Symbol",
        "name": "Name",
        "currency": "Currency",
        "stockExchange": "Exchange",
        "exchangeShortName": "Exchange Code",
    })

    df = df.drop(columns=["Exchange Code"], errors="ignore")
    if "Symbol" in df.columns:
        df = df.set_index("Symbol").sort_index()
    return df